### ISSUE TITLE
Change in source data: some column names missing

### ISSUE THREAD

**Issue by maxwellwood** [Covid19R/covid19nytimes#3]
The following names were missing in the 2020-04-26 17:22:42 refresh of covid19nytimes:
location_code
location_code_type

**Comment by aedobbyn** [comment]
^ sorry, test issue using the `gh` package -- not sure why this didn't post under my username!

**Comment by jebyrnes** [comment]
Have not used the gh package. This is AMAZING!

On Apr 26, 2020, at 5:32 PM, Amanda Dobbyn <notifications@github.com> wrote:

﻿
[EXTERNAL SENDER]

Closed #3<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCovid19R%2Fcovid19nytimes%2Fissues%2F3&data=02%7C01%7Cjarrett.byrnes%40umb.edu%7C83e75a33da52417e3c7908d7ea295804%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637235335619833390&sdata=erieDU8uFkva0%2Fq9Ae8uJOXUmzidFOiGwF2xSxxD714%3D&reserved=0>.
